version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console/UI Port
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: minio_setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Tunggu MinIO nyala...';
      sleep 5;
      
      echo 'Setup alias MinIO client...';
      mc alias set minio http://minio:9000 admin password123;
      
      echo 'Bikin bucket (kalau belum ada)...';
      mc mb minio/taupay --ignore-existing;
      
      echo 'Set permission public khusus directory product/...';
      mc anonymous set download minio/taupay/product;
      
      echo 'Setup selesai!';
      exit 0;
      "

volumes:
  minio_data: